# Configurations for Grow-and-Prune

# Author : Shikhar Tuli

grow:
  num_ops: 1
  feed_forward_grow_dim: 1024 

num_grow_samples:
  5

prune:
  num_ops: 2
  num_feed_forward_layers: 2
  feed_forward_prune_dim: 128
  hidden_prune_dim: 48

model_transfer_mode:
  RP

allowed_ops:
  - sa_sdp
  - sa_wma 
  - l_dft
  - l_dct
  - c_5
  - c_9
  - c_13